all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    master_name: master

master:
  hosts:
    cl1-master:
      ansible_host: 10.0.2.4
      host_name: cl1-master
  vars:
    env: master

worker:
  vars:
    env: worker
  hosts:
    cl1-worker01:
      ansible_host: 10.0.2.5
      host_name: cl1-worker01
    cl1-worker02:
      ansible_host: 10.0.2.6
      host_name: cl1-worker02

Prod:
  children:
    master:
    worker: