all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

Prod:
  hosts:
    cl1-master:
      ansible_host: 192.168.40.50
      env: master
      host_name: cl1-master
    cl1-worker01:
      ansible_host: 192.168.40.51
      env: worker
      host_name: cl1-worker01
      cluster: cl1
      master_name: cl1-master
    cl1-worker02:
      ansible_host: 192.168.40.52
      env: worker
      host_name: cl1-worker02
      cluster: cl1
      master_name: cl1-master
    cl2-master:
      ansible_host: 192.168.40.60
      env: master
      host_name: cl2-master
    cl2-worker01:
      ansible_host: 192.168.40.61       
      env: worker
      host_name: cl2-worker01
      cluster: cl2
      master_name: cl1-master
