all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    master_local_address: 172.31.28.65

master:
  hosts:
    cl1-master:
      ansible_host: 54.235.60.142
      host_name: cl1-master
  vars:
    env: master

worker:
  vars:
    env: worker
  hosts:
    cl1-worker01:
      ansible_host: 3.239.186.20
      host_name: cl1-worker01
    cl1-worker02:
      ansible_host: 3.238.141.169
      host_name: cl1-worker02

Prod:
  children:
    master:
    worker: