all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    master_name: master

master:
  hosts:
    cl1-master:
      ansible_host: 44.192.89.17
      host_name: cl1-master
  vars:
    env: master

worker:
  vars:
    env: worker
  hosts:
    cl1-worker01:
      ansible_host: 44.197.182.193
      host_name: cl1-worker01
    cl1-worker02:
      ansible_host: 3.92.205.50
      host_name: cl1-worker02

Prod:
  children:
    master:
    worker: